/**
 * Datos de ejemplo para ver el CRM lleno. Todo es ficticio.
 *
 * Todos los teléfonos empiezan por PREFIJO_DEMO (+59322…, rango de fijos de
 * Quito que el agente nunca recibe por WhatsApp): así `pnpm db:demo --borrar`
 * los encuentra y los borra sin tocar un solo dato real.
 */
export const PREFIJO_DEMO = '+5932200'

export type TipoDemo = 'clinica' | 'restaurante' | 'hotel' | 'particular' | 'otro'

export type ClienteDemo = {
  contacto: string
  negocio: string | null
  tipo: TipoDemo
  canal: 'whatsapp_agente' | 'presencial'
  consolidado?: boolean
  direccion: string
  /** Cuántos pedidos tiene. 0 = lead que todavía no compra. */
  pedidos: number
  temperatura: 'frio' | 'tibio' | 'caliente'
  necesidad: string
  ultimoMensaje: string
  escalado?: boolean
}

export const CLIENTES_DEMO: ClienteDemo[] = [
  {
    contacto: 'Dra. Paola Andrade',
    negocio: 'Clínica Dental Sonrisa Norte',
    tipo: 'clinica',
    canal: 'whatsapp_agente',
    consolidado: true,
    direccion: 'Av. Amazonas N39-12 y Pereira',
    pedidos: 4,
    temperatura: 'caliente',
    necesidad: 'Lavado semanal de mandiles y toallas',
    ultimoMensaje: '¿Pueden pasar el jueves por los mandiles?',
  },
  {
    contacto: 'Lcdo. Marco Salazar',
    negocio: 'Centro Médico La Kennedy',
    tipo: 'clinica',
    canal: 'whatsapp_agente',
    direccion: 'Calle Los Pinos E12-45',
    pedidos: 3,
    temperatura: 'caliente',
    necesidad: 'Sábanas y batas de consultorio',
    ultimoMensaje: 'Confirmo la recolección de mañana',
  },
  {
    contacto: 'Andrea Villacís',
    negocio: 'Fisioterapia Movimiento',
    tipo: 'clinica',
    canal: 'whatsapp_agente',
    direccion: 'Av. Eloy Alfaro N47-80',
    pedidos: 2,
    temperatura: 'tibio',
    necesidad: 'Toallas y fundas de camilla',
    ultimoMensaje: '¿El combo incluye ida y vuelta?',
  },
  {
    contacto: 'Dr. Felipe Muñoz',
    negocio: 'Veterinaria Patitas',
    tipo: 'clinica',
    canal: 'whatsapp_agente',
    direccion: 'Av. De los Granados E14-22',
    pedidos: 0,
    temperatura: 'caliente',
    necesidad: 'Cotizar lavado de mantas de mascotas',
    ultimoMensaje: '¿Cuánto sale por kilo si son mantas grandes?',
  },
  {
    contacto: 'Karla Espinosa',
    negocio: 'Spa Dermatológico Aura',
    tipo: 'clinica',
    canal: 'whatsapp_agente',
    direccion: 'Av. Portugal E10-60',
    pedidos: 0,
    temperatura: 'tibio',
    necesidad: 'Batas y toallas de spa',
    ultimoMensaje: 'Lo converso con mi socia y le aviso',
  },
  {
    contacto: 'Chef Rodrigo Pazmiño',
    negocio: 'Restaurante El Fogón Quiteño',
    tipo: 'restaurante',
    canal: 'whatsapp_agente',
    consolidado: true,
    direccion: 'Av. 6 de Diciembre N34-51',
    pedidos: 5,
    temperatura: 'caliente',
    necesidad: 'Manteles y mandiles de cocina cada semana',
    ultimoMensaje: 'Esta semana van 12 manteles medianos',
  },
  {
    contacto: 'Gabriela Torres',
    negocio: 'Cafetería Grano de Oro',
    tipo: 'restaurante',
    canal: 'whatsapp_agente',
    direccion: 'Calle Pedro Barrios N45-10',
    pedidos: 3,
    temperatura: 'tibio',
    necesidad: 'Mandiles de baristas',
    ultimoMensaje: 'Gracias, llegó todo impecable',
  },
  {
    contacto: 'Luis Cabrera',
    negocio: 'Pizzería Napoli Express',
    tipo: 'restaurante',
    canal: 'whatsapp_agente',
    direccion: 'Av. Galo Plaza Lasso N60-24',
    pedidos: 2,
    temperatura: 'tibio',
    necesidad: 'Manteles pequeños',
    ultimoMensaje: '¿Me recuerdan el total?',
  },
  {
    contacto: 'María José Ortiz',
    negocio: 'Cevichería La Costeña',
    tipo: 'restaurante',
    canal: 'whatsapp_agente',
    direccion: 'Av. Real Audiencia N58-33',
    pedidos: 0,
    temperatura: 'frio',
    necesidad: 'Consulta de precios de manteles',
    ultimoMensaje: 'Solo estaba averiguando precios',
  },
  {
    contacto: 'Esteban Ruiz',
    negocio: 'Sushi Kaizen',
    tipo: 'restaurante',
    canal: 'whatsapp_agente',
    direccion: 'Av. República de El Salvador N35-40',
    pedidos: 0,
    temperatura: 'caliente',
    necesidad: 'Servicio semanal para 3 locales',
    ultimoMensaje: 'Quiero hablar con alguien para un contrato mensual',
    escalado: true,
  },
  {
    contacto: 'Fernanda Lozada',
    negocio: 'Hotel Boutique Los Andes',
    tipo: 'hotel',
    canal: 'whatsapp_agente',
    consolidado: true,
    direccion: 'Av. Juan León Mera N23-15',
    pedidos: 5,
    temperatura: 'caliente',
    necesidad: 'Edredones y sábanas de 18 habitaciones',
    ultimoMensaje: 'Mañana salen 10 edredones de 2 plazas',
  },
  {
    contacto: 'Jorge Benítez',
    negocio: 'Hostal Mitad del Mundo',
    tipo: 'hotel',
    canal: 'whatsapp_agente',
    direccion: 'Calle Carrión E7-32',
    pedidos: 3,
    temperatura: 'tibio',
    necesidad: 'Edredones y cortinas',
    ultimoMensaje: '¿Lavan cortinas pesadas?',
  },
  {
    contacto: 'Sofía Guerrero',
    negocio: 'Apart Hotel Cumbayá Suites',
    tipo: 'hotel',
    canal: 'whatsapp_agente',
    direccion: 'Av. Interoceánica km 12',
    pedidos: 2,
    temperatura: 'tibio',
    necesidad: 'Duvets y almohadas',
    ultimoMensaje: 'Perfecto, quedo atenta',
  },
  {
    contacto: 'Ricardo Vega',
    negocio: 'Hotel Ejecutivo Carolina',
    tipo: 'hotel',
    canal: 'whatsapp_agente',
    direccion: 'Av. Shyris N36-120',
    pedidos: 0,
    temperatura: 'caliente',
    necesidad: 'Cotizar 40 edredones de 3 plazas',
    ultimoMensaje: '¿Hacen descuento por volumen?',
  },
  {
    contacto: 'Daniela Proaño',
    negocio: 'Hostería Valle Verde',
    tipo: 'hotel',
    canal: 'whatsapp_agente',
    direccion: 'Tumbaco, calle Francisco de Orellana',
    pedidos: 0,
    temperatura: 'tibio',
    necesidad: 'Cortinas visillos del salón',
    ultimoMensaje: '¿Recogen en Tumbaco?',
  },
  {
    contacto: 'Verónica Chávez',
    negocio: null,
    tipo: 'particular',
    canal: 'presencial',
    direccion: '',
    pedidos: 3,
    temperatura: 'tibio',
    necesidad: 'Ternos y camisas',
    ultimoMensaje: '',
  },
  {
    contacto: 'Patricio Mena',
    negocio: null,
    tipo: 'particular',
    canal: 'presencial',
    direccion: '',
    pedidos: 2,
    temperatura: 'tibio',
    necesidad: 'Edredones de la casa',
    ultimoMensaje: '',
  },
  {
    contacto: 'Lucía Herrera',
    negocio: null,
    tipo: 'particular',
    canal: 'whatsapp_agente',
    direccion: 'Calle Isla Floreana N42-18',
    pedidos: 2,
    temperatura: 'tibio',
    necesidad: 'Vestido de fiesta y chompas',
    ultimoMensaje: '¿Ya está listo mi vestido?',
  },
  {
    contacto: 'Andrés Cordero',
    negocio: null,
    tipo: 'particular',
    canal: 'presencial',
    direccion: '',
    pedidos: 1,
    temperatura: 'frio',
    necesidad: 'Zapatos deportivos',
    ultimoMensaje: '',
  },
  {
    contacto: 'Camila Reyes',
    negocio: null,
    tipo: 'particular',
    canal: 'whatsapp_agente',
    direccion: 'Av. El Inca E8-100',
    pedidos: 0,
    temperatura: 'frio',
    necesidad: 'Precio de vestido de novia',
    ultimoMensaje: '¿Cuánto cuesta un vestido de novia con cola?',
  },
  {
    contacto: 'Tomás Aguirre',
    negocio: null,
    tipo: 'particular',
    canal: 'whatsapp_agente',
    direccion: 'Calle Río Coca E10-5',
    pedidos: 0,
    temperatura: 'tibio',
    necesidad: 'Alfombra de sala',
    ultimoMensaje: 'Me dañaron una prenda la otra vez en otra lavandería, ¿ustedes garantizan?',
    escalado: true,
  },
  {
    contacto: 'Diego Paredes',
    negocio: 'Gimnasio Power Fit',
    tipo: 'otro',
    canal: 'whatsapp_agente',
    direccion: 'Av. De la Prensa N52-14',
    pedidos: 3,
    temperatura: 'caliente',
    necesidad: 'Toallas de socios',
    ultimoMensaje: 'Pasen el lunes por favor',
  },
  {
    contacto: 'Silvia Romero',
    negocio: 'Escuela de Danza Ritmo',
    tipo: 'otro',
    canal: 'whatsapp_agente',
    direccion: 'Calle Tomás de Berlanga E11-20',
    pedidos: 0,
    temperatura: 'frio',
    necesidad: 'Trajes de presentación',
    ultimoMensaje: 'Gracias, lo tendré en cuenta',
  },
  {
    contacto: 'Pablo Jaramillo',
    negocio: 'Coworking Hub 593',
    tipo: 'otro',
    canal: 'presencial',
    direccion: '',
    pedidos: 1,
    temperatura: 'tibio',
    necesidad: 'Cortinas de salas de reunión',
    ultimoMensaje: '',
  },
]
